### ISSUE TITLE
Intents problem

### ISSUE THREAD

**Issue by PurpleBored** [Gabriel-M-Martins/Discord-MusicBot#5]
When trying to run the main.py i get a error like this 
Traceback (most recent call last):
  File "C:\BOT\main.py", line 20, in <module>
    bot = commands.Bot(command_prefix='/')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BotBase.__init__() missing 1 required keyword-only argument: 'intents'

**Comment by Gabriel-M-Martins** [comment]
just merged a pr that fixes it. sorry for leaving you waiting.
